[package]
name = "day02"
version = "0.1.0"
authors = ["Gijs van der Voort <vandervoort.gijs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
